deck = [
    {'Card':'A', 'Suit':'Clubs', 'Emoji' : 'A♣', 'Point': 1, 'Imgage':'assets/card/Ac.png'},
    {'Card':'A', 'Suit':'Diamonds', 'Emoji' : 'A♦', 'Point': 1, 'Imgage':'assets/card/Ad.png'},
    {'Card':'A', 'Suit':'Hearts', 'Emoji' : 'A♥', 'Point': 1, 'Imgage':'assets/card/Ah.png'},
    {'Card':'A', 'Suit':'Spades', 'Emoji' : 'A♠', 'Point': 1, 'Imgage':'assets/card/As.png'},
    {'Card':'2', 'Suit':'Clubs', 'Emoji' : '2♣', 'Point': 2, 'Imgage':'assets/card/2c.png'},
    {'Card':'2', 'Suit':'Diamonds', 'Emoji' : '2♦', 'Point': 2, 'Imgage':'assets/card/2d.png'},
    {'Card':'2', 'Suit':'Hearts', 'Emoji' : '2♥', 'Point': 2, 'Imgage':'assets/card/2h.png'},
    {'Card':'2', 'Suit':'Spades', 'Emoji' : '2♠', 'Point': 2, 'Imgage':'assets/card/2s.png'},
    {'Card':'3', 'Suit':'Clubs', 'Emoji' : '3♣', 'Point': 3, 'Imgage':'assets/card/3c.png'},
    {'Card':'3', 'Suit':'Diamonds', 'Emoji' : '3♦', 'Point': 3, 'Imgage':'assets/card/3d.png'},
    {'Card':'3', 'Suit':'Hearts', 'Emoji' : '3♥', 'Point': 3, 'Imgage':'assets/card/3h.png'},
    {'Card':'3', 'Suit':'Spades', 'Emoji' : '3♠', 'Point': 3, 'Imgage':'assets/card/3s.png'},
    {'Card':'4', 'Suit':'Clubs', 'Emoji' : '4♣', 'Point': 4, 'Imgage':'assets/card/4c.png'},
    {'Card':'4', 'Suit':'Diamonds', 'Emoji' : '4♦', 'Point': 4, 'Imgage':'assets/card/4d.png'},
    {'Card':'4', 'Suit':'Hearts', 'Emoji' : '4♥', 'Point': 4, 'Imgage':'assets/card/4h.png'},
    {'Card':'4', 'Suit':'Spades', 'Emoji' : '4♠', 'Point': 4, 'Imgage':'assets/card/4s.png'},
    {'Card':'5', 'Suit':'Clubs', 'Emoji' : '5♣', 'Point': 5, 'Imgage':'assets/card/5c.png'},
    {'Card':'5', 'Suit':'Diamonds', 'Emoji' : '5♦', 'Point': 5, 'Imgage':'assets/card/5d.png'},
    {'Card':'5', 'Suit':'Hearts', 'Emoji' : '5♥', 'Point': 5, 'Imgage':'assets/card/5h.png'},
    {'Card':'5', 'Suit':'Spades', 'Emoji' : '5♠', 'Point': 5, 'Imgage':'assets/card/5s.png'},
    {'Card':'6', 'Suit':'Clubs', 'Emoji' : '6♣', 'Point': 6, 'Imgage':'assets/card/6c.png'},
    {'Card':'6', 'Suit':'Diamonds', 'Emoji' : '6♦', 'Point': 6, 'Imgage':'assets/card/6d.png'},
    {'Card':'6', 'Suit':'Hearts', 'Emoji' : '6♥', 'Point': 6, 'Imgage':'assets/card/6h.png'},
    {'Card':'6', 'Suit':'Spades', 'Emoji' : '6♠', 'Point': 6, 'Imgage':'assets/card/6s.png'},
    {'Card':'7', 'Suit':'Clubs', 'Emoji' : '7♣', 'Point': 7, 'Imgage':'assets/card/7c.png'},
    {'Card':'7', 'Suit':'Diamonds', 'Emoji' : '7♦', 'Point': 7, 'Imgage':'assets/card/7d.png'},
    {'Card':'7', 'Suit':'Hearts', 'Emoji' : '7♥', 'Point': 7, 'Imgage':'assets/card/7h.png'},
    {'Card':'7', 'Suit':'Spades', 'Emoji' : '7♠', 'Point': 7, 'Imgage':'assets/card/7s.png'},
    {'Card':'8', 'Suit':'Clubs', 'Emoji' : '8♣', 'Point': 8, 'Imgage':'assets/card/8c.png'},
    {'Card':'8', 'Suit':'Diamonds', 'Emoji' : '8♦', 'Point': 8, 'Imgage':'assets/card/8d.png'},
    {'Card':'8', 'Suit':'Hearts', 'Emoji' : '8♥', 'Point': 8, 'Imgage':'assets/card/8h.png'},
    {'Card':'8', 'Suit':'Spades', 'Emoji' : '8♠', 'Point': 8, 'Imgage':'assets/card/8s.png'},
    {'Card':'9', 'Suit':'Clubs', 'Emoji' : '9♣', 'Point': 9, 'Imgage':'assets/card/9c.png'},
    {'Card':'9', 'Suit':'Diamonds', 'Emoji' : '9♦', 'Point': 9, 'Imgage':'assets/card/9d.png'},
    {'Card':'9', 'Suit':'Hearts', 'Emoji' : '9♥', 'Point': 9, 'Imgage':'assets/card/9h.png'},
    {'Card':'9', 'Suit':'Spades', 'Emoji' : '9♠', 'Point': 9, 'Imgage':'assets/card/9s.png'},
    {'Card':'10', 'Suit':'Clubs', 'Emoji' : '10♣', 'Point': 0, 'Imgage':'assets/card/10c.png'},
    {'Card':'10', 'Suit':'Diamonds', 'Emoji' : '10♦', 'Point': 0, 'Imgage':'assets/card/10d.png'},
    {'Card':'10', 'Suit':'Hearts', 'Emoji' : '10♥', 'Point': 0, 'Imgage':'assets/card/10h.png'},
    {'Card':'10', 'Suit':'Spades', 'Emoji' : '10♠', 'Point': 0, 'Imgage':'assets/card/10s.png'},
    {'Card':'J', 'Suit':'Clubs', 'Emoji' : 'J♣', 'Point': 0, 'Imgage':'assets/card/jc.png'},  
    {'Card':'J', 'Suit':'Diamonds', 'Emoji' : 'J♦', 'Point': 0, 'Imgage':'assets/card/jd.png'},
    {'Card':'J', 'Suit':'Hearts', 'Emoji' : 'J♥', 'Point': 0, 'Imgage':'assets/card/jh.png'},
    {'Card':'J', 'Suit':'Spades', 'Emoji' : 'J♠', 'Point': 0, 'Imgage':'assets/card/js.png'},
    {'Card':'Q', 'Suit':'Clubs', 'Emoji' : 'Q♣', 'Point': 0, 'Imgage':'assets/card/qc.png'},
    {'Card':'Q', 'Suit':'Diamonds', 'Emoji' : 'Q♦', 'Point': 0, 'Imgage':'assets/card/qd.png'},
    {'Card':'Q', 'Suit':'Hearts', 'Emoji' : 'Q♥', 'Point': 0, 'Imgage':'assets/card/qh.png'},
    {'Card':'Q', 'Suit':'Spades', 'Emoji' : 'Q♠', 'Point': 0, 'Imgage':'assets/card/qs.png'},
    {'Card':'K', 'Suit':'Clubs', 'Emoji' : 'K♣', 'Point': 0, 'Imgage':'assets/card/kc.png'},
    {'Card':'K', 'Suit':'Diamonds', 'Emoji' : 'K♦', 'Point': 0, 'Imgage':'assets/card/kd.png'},
    {'Card':'K', 'Suit':'Hearts', 'Emoji' : 'K♥', 'Point': 0, 'Imgage':'assets/card/kh.png'},
    {'Card':'K', 'Suit':'Spades', 'Emoji' : 'K♠', 'Point': 0, 'Imgage':'assets/card/ks.png'}
    ]

NoneCard = {'Card':'None', 'Suit':'', 'Point': 0, 'Emoji' : '', 'Imgage':'assets/Nonecard.png'}

def create_new_deck():
    deck_loop = deck.copy()
    return deck_loop