deck = [
    {'Card':'A', 'Suit':'Clubs', 'Emoji' : 'A♣', 'Unicode': '🃑', 'Point': 1, 'Imgage':'Ac.png'},
    {'Card':'A', 'Suit':'Diamonds', 'Emoji' : 'A♦', 'Unicode': '🃁', 'Point': 1, 'Imgage':'Ad.png'},
    {'Card':'A', 'Suit':'Hearts', 'Emoji' : 'A♥', 'Unicode': '🂱', 'Point': 1, 'Imgage':'Ah.png'},
    {'Card':'A', 'Suit':'Spades', 'Emoji' : 'A♠', 'Unicode': '🂡', 'Point': 1, 'Imgage':'As.png'},
    {'Card':'2', 'Suit':'Clubs', 'Emoji' : '2♣', 'Unicode': '🃒', 'Point': 2, 'Imgage':'2c.png'},
    {'Card':'2', 'Suit':'Diamonds', 'Emoji' : '2♦', 'Unicode': '🃂', 'Point': 2, 'Imgage':'2d.png'},
    {'Card':'2', 'Suit':'Hearts', 'Emoji' : '2♥', 'Unicode': '🂲', 'Point': 2, 'Imgage':'2h.png'},
    {'Card':'2', 'Suit':'Spades', 'Emoji' : '2♠', 'Unicode': '🂢', 'Point': 2, 'Imgage':'2s.png'},
    {'Card':'3', 'Suit':'Clubs', 'Emoji' : '3♣', 'Unicode': '🃓', 'Point': 3, 'Imgage':'3c.png'},
    {'Card':'3', 'Suit':'Diamonds', 'Emoji' : '3♦', 'Unicode': '🃃', 'Point': 3, 'Imgage':'3d.png'},
    {'Card':'3', 'Suit':'Hearts', 'Emoji' : '3♥', 'Unicode': '🂳', 'Point': 3, 'Imgage':'3h.png'},
    {'Card':'3', 'Suit':'Spades', 'Emoji' : '3♠', 'Unicode': '🂣', 'Point': 3, 'Imgage':'3s.png'},
    {'Card':'4', 'Suit':'Clubs', 'Emoji' : '4♣', 'Unicode': '🃔', 'Point': 4, 'Imgage':'4c.png'},
    {'Card':'4', 'Suit':'Diamonds', 'Emoji' : '4♦', 'Unicode': '🃄', 'Point': 4, 'Imgage':'4d.png'},
    {'Card':'4', 'Suit':'Hearts', 'Emoji' : '4♥', 'Unicode': '🂴', 'Point': 4, 'Imgage':'4h.png'},
    {'Card':'4', 'Suit':'Spades', 'Emoji' : '4♠', 'Unicode': '🂤', 'Point': 4, 'Imgage':'4s.png'},
    {'Card':'5', 'Suit':'Clubs', 'Emoji' : '5♣', 'Unicode': '🃕', 'Point': 5, 'Imgage':'5c.png'},
    {'Card':'5', 'Suit':'Diamonds', 'Emoji' : '5♦', 'Unicode': '🃅', 'Point': 5, 'Imgage':'5d.png'},
    {'Card':'5', 'Suit':'Hearts', 'Emoji' : '5♥', 'Unicode': '🂵', 'Point': 5, 'Imgage':'5h.png'},
    {'Card':'5', 'Suit':'Spades', 'Emoji' : '5♠', 'Unicode': '🂥', 'Point': 5, 'Imgage':'5s.png'},
    {'Card':'6', 'Suit':'Clubs', 'Emoji' : '6♣', 'Unicode': '🃖', 'Point': 6, 'Imgage':'6c.png'},
    {'Card':'6', 'Suit':'Diamonds', 'Emoji' : '6♦', 'Unicode': '🃆', 'Point': 6, 'Imgage':'6d.png'},
    {'Card':'6', 'Suit':'Hearts', 'Emoji' : '6♥', 'Unicode': '🂶', 'Point': 6, 'Imgage':'6h.png'},
    {'Card':'6', 'Suit':'Spades', 'Emoji' : '6♠', 'Unicode': '🂦', 'Point': 6, 'Imgage':'6s.png'},
    {'Card':'7', 'Suit':'Clubs', 'Emoji' : '7♣', 'Unicode': '🃗', 'Point': 7, 'Imgage':'7c.png'},
    {'Card':'7', 'Suit':'Diamonds', 'Emoji' : '7♦', 'Unicode': '🃇', 'Point': 7, 'Imgage':'7d.png'},
    {'Card':'7', 'Suit':'Hearts', 'Emoji' : '7♥', 'Unicode': '🂷', 'Point': 7, 'Imgage':'7h.png'},
    {'Card':'7', 'Suit':'Spades', 'Emoji' : '7♠', 'Unicode': '🂧', 'Point': 7, 'Imgage':'7s.png'},
    {'Card':'8', 'Suit':'Clubs', 'Emoji' : '8♣', 'Unicode': '🃘', 'Point': 8, 'Imgage':'8c.png'},
    {'Card':'8', 'Suit':'Diamonds', 'Emoji' : '8♦', 'Unicode': '🃈', 'Point': 8, 'Imgage':'8d.png'},
    {'Card':'8', 'Suit':'Hearts', 'Emoji' : '8♥', 'Unicode': '🂸', 'Point': 8, 'Imgage':'8h.png'},
    {'Card':'8', 'Suit':'Spades', 'Emoji' : '8♠', 'Unicode': '🂨', 'Point': 8, 'Imgage':'8s.png'},
    {'Card':'9', 'Suit':'Clubs', 'Emoji' : '9♣', 'Unicode': '🃙', 'Point': 9, 'Imgage':'9c.png'},
    {'Card':'9', 'Suit':'Diamonds', 'Emoji' : '9♦', 'Unicode': '🃉', 'Point': 9, 'Imgage':'9d.png'},
    {'Card':'9', 'Suit':'Hearts', 'Emoji' : '9♥', 'Unicode': '🂹', 'Point': 9, 'Imgage':'9h.png'},
    {'Card':'9', 'Suit':'Spades', 'Emoji' : '9♠', 'Unicode': '🂩', 'Point': 9, 'Imgage':'9s.png'},
    {'Card':'10', 'Suit':'Clubs', 'Emoji' : '10♣', 'Unicode': '🃚', 'Point': 10, 'Imgage':'10c.png'},
    {'Card':'10', 'Suit':'Diamonds', 'Emoji' : '10♦', 'Unicode': '🃊', 'Point': 10, 'Imgage':'10d.png'},
    {'Card':'10', 'Suit':'Hearts', 'Emoji' : '10♥', 'Unicode': '🂺', 'Point': 10, 'Imgage':'10h.png'},
    {'Card':'10', 'Suit':'Spades', 'Emoji' : '10♠', 'Unicode': '🂪', 'Point': 10, 'Imgage':'10s.png'},
    {'Card':'J', 'Suit':'Clubs', 'Emoji' : 'J♣', 'Unicode': '🃛', 'Point': 0, 'Imgage':'jc.png'},  
    {'Card':'J', 'Suit':'Diamonds', 'Emoji' : 'J♦', 'Unicode': '🃋', 'Point': 0, 'Imgage':'jd.png'},
    {'Card':'J', 'Suit':'Hearts', 'Emoji' : 'J♥', 'Unicode': '🂻', 'Point': 0, 'Imgage':'jh.png'},
    {'Card':'J', 'Suit':'Spades', 'Emoji' : 'J♠', 'Unicode': '🂫', 'Point': 0, 'Imgage':'js.png'},
    {'Card':'Q', 'Suit':'Clubs', 'Emoji' : 'Q♣', 'Unicode': '🃝', 'Point': 0, 'Imgage':'qc.png'},
    {'Card':'Q', 'Suit':'Diamonds', 'Emoji' : 'Q♦', 'Unicode': '🃍', 'Point': 0, 'Imgage':'qd.png'},
    {'Card':'Q', 'Suit':'Hearts', 'Emoji' : 'Q♥', 'Unicode': '🂽', 'Point': 0, 'Imgage':'qh.png'},
    {'Card':'Q', 'Suit':'Spades', 'Emoji' : 'Q♠', 'Unicode': '🂭', 'Point': 0, 'Imgage':'qs.png'},
    {'Card':'K', 'Suit':'Clubs', 'Emoji' : 'K♣', 'Unicode': '🃞', 'Point': 0, 'Imgage':'kc.png'},
    {'Card':'K', 'Suit':'Diamonds', 'Emoji' : 'K♦', 'Unicode': '🃎', 'Point': 0, 'Imgage':'kd.png'},
    {'Card':'K', 'Suit':'Hearts', 'Emoji' : 'K♥', 'Unicode': '🂾', 'Point': 0, 'Imgage':'kh.png'},
    {'Card':'K', 'Suit':'Spades', 'Emoji' : 'K♠', 'Unicode': '🂮', 'Point': 0, 'Imgage':'ks.png'}
    ]

NoneCard = {'Card':'', 'Suit':'', 'Point': 0, 'Emoji' : '', 'Imgage':''}